name: Compilar VPK
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compilar
        run: |
          mkdir build && cd build
          cmake ..
          make
      - uses: actions/upload-artifact@v4
        with:
          name: demo-demonios-vpk
          path: build/*.vpk
